### ISSUE TITLE
Unable to define protein features groups Error message

### ISSUE THREAD

**Issue by mpgriesh** [art-egorov/lovis4u#10]
Hi,

I sometimes have input sets of gffs that error after mmseqs clustering because of the above error message. I have looked through DataProcessing.py where the error is thrown but can't figure out what about the input set is causing the error. Can you elaborate why this step might fail? And ideally, can you make the error message more informative?

⦿ 1053 clusters for 1339 proteins were found with mmseqs
mmseqs clustering results were saved to output/mmseqs/mmseqs_clustering.tsv
lovis4uError 💔: Unable to define protein features groups.

Thanks!

**Comment by art-egorov** [comment]
Hi!
Thanks for trying LoVis4u. Could you please run the same command with `-debug` option to see the full traceback message? And if it's possible, could you share the zip archive with input data (if it's not confidential too much, otherwise i'll try to figure out without it)

Best,
Artyom

**Comment by mpgriesh** [comment]
Yeah here is the debug output:

(lovis) [mpgriesh@smsh11dsu-srcf-d15-36 lovis4u]$ lovis4u -gff input/ -o output_2/ -hl -reorient --use-filename-as-id --debug
○ Loaded configuration file: 'standard'. List of available: standard (auto-size),
        A4p1 (A4 page one-column [90mm]), A4p2 (A4 page two-column [190mm]), and A4L (A4 landscape [240mm]).
        Use -c/--config <name> parameter for choosing.
○ Warning: the output folder already exists. Results will be rewritten (without removal other files in this folder)
○ Reading gff files...
⦿ 30 loci were loaded from the gff files folder
○ Running mmseqs for protein clustering...
⦿ 1053 clusters for 1339 proteins were found with mmseqs
        mmseqs clustering results were saved to output_2/mmseqs/mmseqs_clustering.tsv
Traceback (most recent call last):
  File "/labs/asbhatt/mpgriesh/tools/miniconda3/envs/lovis/lib/python3.12/site-packages/lovis4u/DataProcessing.py", line 689, in define_feature_groups
    self.feature_annotation.loc[feature.feature_id, "group"] = feature.group
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/labs/asbhatt/mpgriesh/tools/miniconda3/envs/lovis/lib/python3.12/site-packages/pandas/core/indexing.py", line 911, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/labs/asbhatt/mpgriesh/tools/miniconda3/envs/lovis/lib/python3.12/site-packages/pandas/core/indexing.py", line 1944, in _setitem_with_indexer
    self._setitem_single_block(indexer, value, name)
  File "/labs/asbhatt/mpgriesh/tools/miniconda3/envs/lovis/lib/python3.12/site-packages/pandas/core/indexing.py", line 2189, in _setitem_single_block
    value = self._align_series(indexer, Series(value))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/labs/asbhatt/mpgriesh/tools/miniconda3/envs/lovis/lib/python3.12/site-packages/pandas/core/indexing.py", line 2455, in _align_series
    raise ValueError("Incompatible indexer with Series")
ValueError: Incompatible indexer with Series

The above exception was the direct cause of the following exception:

**Comment by art-egorov** [comment]
Thank you again! 
I will release a new version 0.0.10 in a few minutes which should fix the problem.
Seems there is a case that you have duplicated feature ids in different gff files. If it's the issue, you will get more clear error message with suggestion to use new `--add-locus-id-prefix` (`-alip`) parameter to add contig id prefix to each feature id which can help to fix the problem. 
Let me know if it doesn't help. 

P.S.
Also this version includes a novel essential feature that wasn't implemented before - visualisation of non-CDS feature, including tRNAs, tmRNAs and pseudogenes :) 

Best,
Artyom

**Comment by mpgriesh** [comment]
Thanks Artyom,

This fixed the issue! I am slicing many gffs for features of interest. Sometimes, the feature is duplicated within the window of the slice and then I get two gffs with overlapping features. Those were the ones causing the issue as you point out. The new feature is great too! Some of the features of interest for me are non-coding!

Best,
Matt

**Comment by art-egorov** [comment]
That's great. Thank you again for the report!
If there are any types of gff/gb features you would like to be processed and it's not currently, let me know, i will update :) 

Best,
Artyom
