### ISSUE TITLE
MetaCerberus outputs as inputs for lovis4vis?

### ISSUE THREAD

**Issue by raw-lab** [art-egorov/lovis4u#11]
Good morning,

I don't know if you know about us or not. We provide a front end annotation tool for annotation using HMMs for viruses, phages, archael viruses, bacteria, archaea, and even eukaryotes. 
github.com/raw-lab/metacerberus 

We also produce a gff output etc. I was wondering if you could mention us in your tutorial? We could mention you on our readme/readthedocs. We have had 12k downloads and we are growing. 

Let us know if we can collaborate? We could make yours an automatic plot in our final output. 

Many thanks,
RAW lab

**Comment by art-egorov** [comment]
thanks for the heads up, we’ll have a look :)

**Comment by raw-lab** [comment]
Let us know? We can include yours in a standard output on our end.

**Comment by raw-lab** [comment]
We can send you standard outputs on our end as well to see how we can integrate? 

Many thanks,
RAW Lab
