### ISSUE TITLE
Support suffixes `.gbk` `.gbff` for --gb and `.gff3` for -gff

### ISSUE THREAD

**Issue by gbouras13** [art-egorov/lovis4u#3]
`.gbk` is used by pharokka and phold, .`gbff` and and `.gff3` are used by Bakta - doing this will make it easier for users to use the tool outputs

**Comment by art-egorov** [comment]
Yes, it was definitely an issue, thank you for pointing it out! I've released version 0.0.8, which now ignores suffixes and file names. Instead, if a file is read incorrectly, an error message will be displayed, but the process will continue without terminating if there are other correct files

Best,
Artyom
