### ISSUE TITLE
Does it work for draft genomes?

### ISSUE THREAD

**Issue by ideshigenomics** [art-egorov/lovis4u#4]
I got the following output:

○ Warning: gff file /home/user/Desktop/40_S40_L001.gff contains information for more than 1 sequence. File will be skipped.
○ Warning: gff file /home/user/Desktop/29_S29_L001.gff contains information for more than 1 sequence. File will be skipped.

Please share a sample locus_annotation_table for draft genomes.

**Comment by ideshigenomics** [comment]
Thanks for the quick response. 

Regards,
Tanbir

**Comment by art-egorov** [comment]
No problem! I actually replied the day you asked, but somehow comment wasn't sent... 
I’ll add this feature to the to-do list
Thank you for trying anyway!

Best,
Artyom
