### ISSUE TITLE
Unable to run mmseqs clustering

### ISSUE THREAD

**Issue by scottdossantos** [art-egorov/lovis4u#7]
Hello! I'm having trouble getting the pipeline to run past the mmseqs clustering step and was hoping you could help me out with this.

I installed lovis4u via pip in a fresh conda environment and ran `lovis4u --linux` to correct the mmseqs2 path. I then ran lovis4u on two .gbff files output by bakta (v1.93), which are in their own directory, `gbff/`, using the following:

`lovis4u -gb ./gbff/ -ufid -hl -c A4p2 --set-category-colour --parsing-debug`

However the following error is thrown:

```
○ Reading gb files...
○ Warning: gb file pint_oma14_ctnpi4.gbff was not read properly and skipped
○ Warning: gb file pint_str17_ctnpi1a.gbff was not read properly and skipped
⦿ 0 loci were loaded from genbank files folder
○ Running mmseqs for protein clustering...
lovis4uError 💔: Unable to run mmseqs clustering.
```
Running with `--parsing-debug` shows the following:

```
○ Reading gb files...
○ Warning: gb file pint_oma14_ctnpi4.gbff was not read properly and skipped
Traceback (most recent call last):
  File "/home/dossantos/miniconda3/envs/lovis4u/lib/python3.12/site-packages/lovis4u/DataProcessing.py", line 496, in load_loci_from_gb
    features_ids = [i.qualifiers[id_source][0] for i in gb_CDSs]
                    ~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'protein_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dossantos/miniconda3/envs/lovis4u/lib/python3.12/site-packages/lovis4u/DataProcessing.py", line 549, in load_loci_from_gb
    raise lovis4u.Manager.lovis4uError()
lovis4u.Manager.lovis4uError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dossantos/miniconda3/envs/lovis4u/bin/lovis4u", line 20, in <module>
    loci.load_loci_from_gb(parameters.args["gb"])
  File "/home/dossantos/miniconda3/envs/lovis4u/lib/python3.12/site-packages/lovis4u/DataProcessing.py", line 562, in load_loci_from_gb
    raise lovis4u.Manager.lovis4uError("Unable to load loci from gb folder.") from error
lovis4u.Manager.lovis4uError: Unable to load loci from gb folder.
```

Looks like something to do with the 'protein_id' field?

In any case, I thought I'd try instead to use the .gff3 files that bakta also generates. Lovis4u can read these files without issue, but fails to run MMseqs2:

`lovis4u -gff ./gff/ -ufid -hl -c A4p2 --set-category-colour`

which throws the following error: 

```
○ Reading gff files...
⦿ 2 loci were loaded from genbank files folder
○ Running mmseqs for protein clustering...
lovis4uError 💔: Unable to run mmseqs clustering.
```

When running with `--debug`, this error is shown:

```
○ Reading gff files...
⦿ 2 loci were loaded from genbank files folder
○ Running mmseqs for protein clustering...
Traceback (most recent call last):
  File "/home/dossantos/miniconda3/envs/lovis4u/lib/python3.12/site-packages/lovis4u/DataProcessing.py", line 629, in mmseqs_cluster
    subprocess.run([self.prms.args["mmseqs_binary"], "createdb", temp_input.name,
  File "/home/dossantos/miniconda3/envs/lovis4u/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dossantos/miniconda3/envs/lovis4u/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/dossantos/miniconda3/envs/lovis4u/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/dossantos/miniconda3/envs/lovis4u/lib/python3.12/site-packages/lovis4u/lovis4u_data/bin/mmseqs_mac/bin/mmseqs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dossantos/miniconda3/envs/lovis4u/bin/lovis4u", line 22, in <module>
    mmseqs_clustering_results = loci.mmseqs_cluster()
                                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dossantos/miniconda3/envs/lovis4u/lib/python3.12/site-packages/lovis4u/DataProcessing.py", line 659, in mmseqs_cluster
    raise lovis4u.Manager.lovis4uError("Unable to run mmseqs clustering.") from error
lovis4u.Manager.lovis4uError: Unable to run mmseqs clustering.
```

From what I can tell, it's an issue with `mmseqs createdb`, but I'll admit that I'm not familiar at all with MMseqs. The file, `input_proteins.fa` is definitely being created, though the header lines contain `<unknown description>` after the ID and I'm not sure if this would affect MMSeqs.

I verified that everything was installed correctly by using the example GFFs to create a visualisation and that worked fine, so I'm at a loss as to what's going on here. Is there any advice you could offer? I'm keen to get this working as the visualisations are just beautiful! In the meantime, I'll take a crack at using prokka-generated annotation files and see if I can get it working.

Thanks!

**Comment by art-egorov** [comment]
Hi! Thank you for your report.

For the first issue it seems that your genbank file could have different attributes for ids of CDS objects through the file..
LoVis4u tries by default detect for the first CDS whether its id written as "protein_id" (_genbank_id_source_ config parameter) if it is not, then it tries alternative variants: ID,id,PROTEIN_ID,locus_tag.  
Seems that for the first one it found protein_id attribute but then failed for others. Could you share this file, please? I will try to find the problem and fix it.

For the second problem the issue that you run the command on Linux machine but by default LoVis4u uses mmseqs binary version for Mac, you can easily fix it by running `lovis4u --linux` command. I will change the error message that will make debugging less confusing. 

Best,
Artyom

**Comment by scottdossantos** [comment]
Hi Artyom, thanks so much for the speedy response! 

The two .gbff files are attached (had to add ".txt" to the filename to allow GH to upload). The only features in the GenBank files are source, gene, and CDS

[pint_str17_ctnpi1a.gbff.txt](https://github.com/user-attachments/files/17211099/pint_str17_ctnpi1a.gbff.txt)
[pint_oma14_ctnpi4 copy.gbff.txt](https://github.com/user-attachments/files/17211100/pint_oma14_ctnpi4.copy.gbff.txt)

As for the second issue, I ran `lovis4u --linux` after installing the programme; however I tried again and saw

`⚙ mmseqs path was adjusted to linux`

However running the command again gave me the same error as before. I can get the program to work with the example GFFs, so it looks like the correct version of MMseqs is being used.

Thanks- Scott

**Comment by art-egorov** [comment]
Yes, the problem with the gb files were the one i supposed. I'll release an update today soon to skip such features (seems in that case there is no CDS due to the absence of any reading frame that's why no protein_id for this feature. )

```
     CDS             complement(56964..>57368)
                     /note="Internal stop codon at 56966. Nonsense mutation
                     around 56966."
                     /db_xref="SO:0001217"
                     /db_xref="UniRef:UniRef50_B7BE14"
                     /db_xref="UniRef:UniRef90_G8UQV1"
                     /product="DUF4942 domain-containing protein"
                     /locus_tag="GCOMHB_00290"
                     /pseudogene="unitary"
                     /codon_start=1
                     /transl_table=11
                     /inference="ab initio prediction:Prodigal:2.6"
```    

Regarding the second issue it is strange.. Could you also share thee gff file(s) please..? 
And the debug message is the same even after you switched to the linux version, while for test data it works correctly?

**Comment by scottdossantos** [comment]
Ah that's good to know- thanks! 

As for the second issue, the GFF3 files are attached:

[pint_str17_ctnpi1a.gff3.txt](https://github.com/user-attachments/files/17211708/pint_str17_ctnpi1a.gff3.txt)
[pint_oma14_ctnpi4.gff3.txt](https://github.com/user-attachments/files/17211709/pint_oma14_ctnpi4.gff3.txt)

That's correct. The error messages are the exact same before and after running `lovis4u --linux`, while the test data runs with no problem. Here's what the error looked like before:

```
○ Reading gff files...
⦿ 2 loci were loaded from genbank files folder
○ Running mmseqs for protein clustering...
Traceback (most recent call last):
  File "/home/dossantos/miniconda3/envs/lovis4u/lib/python3.12/site-packages/lovis4u/DataProcessing.py", line 629, in mmseqs_cluster
    subprocess.run([self.prms.args["mmseqs_binary"], "createdb", temp_input.name,
  File "/home/dossantos/miniconda3/envs/lovis4u/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dossantos/miniconda3/envs/lovis4u/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/dossantos/miniconda3/envs/lovis4u/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/dossantos/miniconda3/envs/lovis4u/lib/python3.12/site-packages/lovis4u/lovis4u_data/bin/mmseqs_mac/bin/mmseqs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dossantos/miniconda3/envs/lovis4u/bin/lovis4u", line 22, in <module>
    mmseqs_clustering_results = loci.mmseqs_cluster()
                                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dossantos/miniconda3/envs/lovis4u/lib/python3.12/site-packages/lovis4u/DataProcessing.py", line 659, in mmseqs_cluster
    raise lovis4u.Manager.lovis4uError("Unable to run mmseqs clustering.") from error
lovis4u.Manager.lovis4uError: Unable to run mmseqs clustering.
```

And here is what it looks like after:

```
○ Reading gff files...
⦿ 2 loci were loaded from genbank files folder
○ Running mmseqs for protein clustering...
Traceback (most recent call last):
  File "/home/dossantos/miniconda3/envs/lovis4u/lib/python3.12/site-packages/lovis4u/DataProcessing.py", line 629, in mmseqs_cluster
    subprocess.run([self.prms.args["mmseqs_binary"], "createdb", temp_input.name,
  File "/home/dossantos/miniconda3/envs/lovis4u/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dossantos/miniconda3/envs/lovis4u/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/dossantos/miniconda3/envs/lovis4u/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/dossantos/miniconda3/envs/lovis4u/lib/python3.12/site-packages/lovis4u/lovis4u_data/bin/mmseqs_mac/bin/mmseqs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dossantos/miniconda3/envs/lovis4u/bin/lovis4u", line 22, in <module>
    mmseqs_clustering_results = loci.mmseqs_cluster()
                                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dossantos/miniconda3/envs/lovis4u/lib/python3.12/site-packages/lovis4u/DataProcessing.py", line 659, in mmseqs_cluster
    raise lovis4u.Manager.lovis4uError("Unable to run mmseqs clustering.") from error
lovis4u.Manager.lovis4uError: Unable to run mmseqs clustering.
```

However I did manage to run lovis4u successfully on my local machine (Mac) with the above two GFF3 files.

**Comment by art-egorov** [comment]
Ah, yes, I see the problem.. `lovis4u --linux` command changes only the standard config file, not all fancy I added recently :\

I've fixed the problem for gb files, will fix the config problem now and release the 0.0.9.3 version in several minutes. I'll drop a comment here as well when it's done.

Thank you very much!

**Comment by scottdossantos** [comment]
No, thank **you**- this tool is brilliant!

**Comment by art-egorov** [comment]
Now seems to be fixed. I tested it using the following commands:
`lovis4u -gb gbs -o test  --use-filename-as-id  -hl -reorient ` - for gb file, and
`lovis4u -gff gffs -o test --use-filename-as-id  -hl -reorient ` - for gffs.
as well as with sample data.

You can get the updated version with: `python3 -m pip install lovis4u==0.0.9.3`  
(or via semi-manual installation from GitHub).

Thank you again for the report, and let me know if any issues left.

Best

**Comment by scottdossantos** [comment]
Working like a charm- thanks Artyom!
